# Coppied From: https://dev.to/devangtomar/using-github-pages-and-github-actions-to-deploy-a-react-app-1ge3
name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Installing NPM packages
        run: npm ci

      - name: Building project
        run: npm run build

      # - name: Running tests
      #   run: npm run test

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v4
        with:
          # name: production-files
          path: dist/
      - name: Uploading production-ready build files to GH-pages
        uses: actions/upload-pages-artifact@v3
        with:
          # name: production-files
          path: dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          # name: production-files
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
# End of copied Section